image: ruby:2.6.5

before_script:
  - gem install bundler
  - bundle install

neocities:
  stage: deploy
  environment: neocities
  script:
    - mkdir -p $HOME/.config/neocities
    - mv $NEOCITIES_TOKEN $HOME/.config/neocities/config
    - cd public
    - bundle exec neocities push .
