image: ruby:2.6.5

before_script:
  - gem install bundler
  - bundle install

neocities:
  stage: deploy
  environment: neocities
  script:
    - mkdir -p $HOME/.config/neocities
    - if ["$NEOCITIES_TOKEN" -ne ""]; then mv $NEOCITIES_TOKEN $HOME/.config/neocities/config; else echo Please see README.md for information on how to set your Neocities API token && false; fi
    # If you use a static site generator and it places its output somewhere else,
    # change into that directory instead.
    - cd public
    - bundle exec neocities push .
