before_script:
  - gem install bundler
  - bundle install

stages:
  - build
  - deploy

hugo:
  image: registry.gitlab.com/pages/hugo:latest
  stage: build
  variables:
  GIT_SUBMODULE_STRATEGY: recursive
  pages:
    script:
    - hugo
    artifacts:
      paths:
      - public
    only:
    - master

neocities:
  image: ruby:2.6.5
  stage: deploy
  environment: neocities
  script: 
    # If you use a static site builder, add its build command here
    # Place user-provide token
    - if [ -z "$NEOCITIES_TOKEN" ]; then echo Please see README.md for information on how to set your Neocities API token && false; else mkdir -p $HOME/.config/neocities && mv $NEOCITIES_TOKEN $HOME/.config/neocities/config; fi

    # If you use a static site generator and it places its output somewhere else,
    # change into that directory instead.
    - cd public
    
    # Run the Neocities push
    - bundle exec neocities push .
