name: Build and deploy to neocities

# only run on changes to master
on:
  push:
    branches:
      - master

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: build
        run: hugo --minify
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

#      - name: Deploy to Neocities
#        id: deploy
#        continue-on-error: true
#        uses: bcomnes/deploy-to-neocities@v1
#        with:
#          api_token: ${{ secrets.NEOCITIES_API_KEY }}
#          dist_dir: public
#          cleanup: true

      - name: Deploy to Neocities fallback
        uses: jonchang/deploy-neocities@master
        with:
          key: ${{ secrets.NEOCITIES_API_KEY }}
          dir: public
          clean: true
